pragma solidity ^0.8.28;

/**
 * @title ERC7579InitializedLib
 * @author Rhinestone (zeroknots.eth, highskore.eth)
 * @notice Library for managing ERC7579 module initialization state in a gas-efficient manner
 * @dev This library provides deterministic storage slot generation and state management for
 *      tracking whether ERC7579 modules have been initialized for specific accounts.
 *
 *      The library uses a collision-resistant storage pattern where each account gets a unique
 *      storage slot derived from keccak256(SLOT, account). This ensures complete isolation
 *      between different accounts' initialization states.
 *
 *      Gas optimizations:
 *      - Uses EVM scratch space (0x00-0x3F) instead of allocating memory
 *      - Direct assembly for storage operations
 *      - No unnecessary memory clearing (scratch space is temporary by design)
 *
 * @custom:security All storage slots are deterministically derived and collision-resistant
 */
library ERC7579InitializedLib {
    /// @notice Base storage slot derived from keccak256("ERC7579Module.Initialized.Storage")
    /// @dev This constant ensures consistent storage location across all deployments
    ///      The value 0xd29d5db3 is truncated from the full keccak256 hash
    uint256 internal constant SLOT = 0xd29d5db3;

    /**
     * @notice Computes a unique storage slot for tracking module initialization per account
     * @dev Generates a deterministic storage slot using keccak256(SLOT || account) pattern.
     *      This ensures each account has an isolated storage location that cannot collide
     *      with other accounts or storage variables.
     *
     *      The function uses EVM scratch space (0x00-0x3F) for temporary storage during
     *      hash computation, avoiding memory allocation overhead. The scratch space holds:
     *      - 0x00-0x1F: SLOT constant (base storage identifier)
     *      - 0x20-0x3F: account address (right-padded to 32 bytes)
     *
     * @param account The address for which to generate a storage slot
     * @return _slot The deterministic storage slot for this account's initialization state
     *
     * @custom:gas ~200 gas due to keccak256 operation and scratch space usage
     * @custom:security Collision-resistant due to keccak256 properties and unique inputs
     */
    function moduleSlot(address account) internal pure returns (bytes32 _slot) {
        assembly ("memory-safe") {
            // Use scratch space (0x00-0x3f) to avoid mload(0x40)
            mstore(0x00, SLOT) // Store base slot at 0x00
            mstore(0x20, account) // Store account at 0x20
            _slot := keccak256(0x00, 0x40) // Hash 64 bytes (2 * 32 bytes)
            // No need to clear scratch space - it's meant to be overwritten
        }
    }

    /**
     * @notice Stores a value at the specified storage slot
     * @dev Direct assembly implementation for gas-efficient storage writes.
     *      Typically used to mark a module as initialized (value = 1) or
     *      reset initialization state (value = 0).
     *
     * @param slot The storage slot to write to (generated by moduleSlot)
     * @param value The value to store (usually 0 for uninitialized, 1 for initialized)
     *
     * @custom:gas ~20000 gas for cold storage write, ~5000 for warm storage
     * @custom:usage Common pattern: `set(moduleSlot(account), 1)` to mark as initialized
     */
    function set(bytes32 slot, uint256 value) internal {
        assembly ("memory-safe") {
            sstore(slot, value)
        }
    }

    /**
     * @notice Retrieves the value stored at the specified storage slot
     * @dev Direct assembly implementation for gas-efficient storage reads.
     *      Returns 0 for uninitialized slots (EVM default) or the previously set value.
     *
     * @param slot The storage slot to read from (generated by moduleSlot)
     * @return value The stored value (0 if never set, or the last value written)
     *
     * @custom:gas ~2100 gas for cold storage read, ~100 for warm storage
     * @custom:usage Common pattern: `if (get(moduleSlot(account)) == 0)` to check initialization
     */
    function get(bytes32 slot) internal view returns (uint256 value) {
        assembly ("memory-safe") {
            value := sload(slot)
        }
    }
}
